In [3]:
from chembl_webresource_client.new_client import new_client
import numpy as np, pandas as pd

In [4]:
target=new_client.target.search("CDK2")
targets= pd.DataFrame.from_dict(target)
targets.head()

,cross_references,organism,pref_name,score,species_group_flag,target_chembl_id,target_components,target_type,tax_id
0,[],Homo sapiens,CDK2/CDK4,14.0,False,CHEMBL3038517,"[{'accession': 'P11802', 'component_descriptio...",PROTEIN FAMILY,9606
1,[],Mus musculus,CDK2/CDK4,14.0,False,CHEMBL4106185,"[{'accession': 'P30285', 'component_descriptio...",PROTEIN FAMILY,10090
2,[],Mus musculus,CDK2/CDK9,14.0,False,CHEMBL4106186,"[{'accession': 'Q99J95', 'component_descriptio...",PROTEIN FAMILY,10090
3,[],Homo sapiens,CDK2/Cyclin A2,12.0,False,CHEMBL3038469,"[{'accession': 'P24941', 'component_descriptio...",PROTEIN COMPLEX,9606
4,[],Homo sapiens,CDK2/Cyclin A1,12.0,False,CHEMBL3038470,"[{'accession': 'P24941', 'component_descriptio...",PROTEIN COMPLEX,9606

In [5]:
targets.head(20)

,cross_references,organism,pref_name,score,species_group_flag,target_chembl_id,target_components,target_type,tax_id
0,[],Homo sapiens,CDK2/CDK4,14.0,False,CHEMBL3038517,"[{'accession': 'P11802', 'component_descriptio...",PROTEIN FAMILY,9606
1,[],Mus musculus,CDK2/CDK4,14.0,False,CHEMBL4106185,"[{'accession': 'P30285', 'component_descriptio...",PROTEIN FAMILY,10090
2,[],Mus musculus,CDK2/CDK9,14.0,False,CHEMBL4106186,"[{'accession': 'Q99J95', 'component_descriptio...",PROTEIN FAMILY,10090
3,[],Homo sapiens,CDK2/Cyclin A2,12.0,False,CHEMBL3038469,"[{'accession': 'P24941', 'component_descriptio...",PROTEIN COMPLEX,9606
4,[],Homo sapiens,CDK2/Cyclin A1,12.0,False,CHEMBL3038470,"[{'accession': 'P24941', 'component_descriptio...",PROTEIN COMPLEX,9606
5,[],Homo sapiens,CDK2/Cyclin O,12.0,False,CHEMBL4106152,"[{'accession': 'P24941', 'component_descriptio...",PROTEIN COMPLEX,9606
6,[],Homo sapiens,CDK2/Cyclin-E2,12.0,False,CHEMBL4523633,"[{'accession': 'P24941', 'component_descriptio...",PROTEIN COMPLEX,9606
7,[],Homo sapiens,CDK2/Cyclin-Y,12.0,False,CHEMBL4523634,"[{'accession': 'P24941', 'component_descriptio...",PROTEIN COMPLEX,9606
8,[],Homo sapiens,CDK2/Cyclin C,12.0,False,CHEMBL4888454,"[{'accession': 'P24941', 'component_descriptio...",PROTEIN COMPLEX,9606
9,"[{'xref_id': 'P24941', 'xref_name': None, 'xre...",Homo sapiens,Cyclin-dependent kinase 2,11.0,False,CHEMBL301,"[{'accession': 'P24941', 'component_descriptio...",SINGLE PROTEIN,9606
10,[],Homo sapiens,CDK2/Bovine cyclin A,11.0,False,CHEMBL4106153,"[{'accession': 'P24941', 'component_descriptio...",PROTEIN COMPLEX,9606
11,[],Homo sapiens,Protein cereblon/Cyclin-dependent kinase 2,11.0,False,CHEMBL4523689,"[{'accession': 'P24941', 'component_descriptio...",PROTEIN-PROTEIN INTERACTION,9606
12,[],Mus musculus,Cereblon/Cyclin-dependent kinase 2,11.0,False,CHEMBL4802027,"[{'accession': 'P97377', 'component_descriptio...",PROTEIN-PROTEIN INTERACTION,10090
13,"[{'xref_id': 'O75956', 'xref_name': None, 'xre...",Homo sapiens,Cyclin-dependent kinase 2-associated protein 2,10.0,False,CHEMBL6010,"[{'accession': 'O75956', 'component_descriptio...",SINGLE PROTEIN,9606
14,[],Homo sapiens,Cyclin-dependent kinase 2/cyclin E1,10.0,False,CHEMBL1907605,"[{'accession': 'P24864', 'component_descriptio...",PROTEIN COMPLEX,9606
15,"[{'xref_id': 'P00546', 'xref_name': None, 'xre...",Saccharomyces cerevisiae S288c,Cell division control protein 28,9.0,False,CHEMBL5213,"[{'accession': 'P00546', 'component_descriptio...",SINGLE PROTEIN,559292
16,"[{'xref_id': 'O14519', 'xref_name': None, 'xre...",Homo sapiens,Cyclin-dependent kinase 2-associated protein 1,9.0,False,CHEMBL5578,"[{'accession': 'O14519', 'component_descriptio...",SINGLE PROTEIN,9606
17,"[{'xref_id': 'EBI-768477', 'xref_name': None, ...",Homo sapiens,Cyclin-dependent kinase 2/cyclin E,9.0,False,CHEMBL2094126,"[{'accession': 'P24864', 'component_descriptio...",PROTEIN COMPLEX,9606
18,"[{'xref_id': 'EBI-767671', 'xref_name': None, ...",Homo sapiens,Cyclin-dependent kinase 2/cyclin A,9.0,False,CHEMBL2094128,"[{'accession': 'P24941', 'component_descriptio...",PROTEIN COMPLEX,9606
19,[],Homo sapiens,Cyclin-dependent kinase 2 and 4 (CDK2 and CDK4),9.0,False,CHEMBL2111326,"[{'accession': 'P11802', 'component_descriptio...",SELECTIVITY GROUP,9606

In [6]:
selected_target=targets.target_chembl_id[9]
selected_target

'CHEMBL301'

In [7]:
activity=new_client.activity
res=activity.filter(target_chembl_id=selected_target)
df_all_types=pd.DataFrame.from_dict(res)
df_all_types.head()

,action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
0,None,None,105376,[],CHEMBL660784,Inhibitory concentration against cyclin-depend...,B,None,None,BAO_0000190,...,Homo sapiens,Cyclin-dependent kinase 2,9606,None,None,IC50,uM,UO_0000065,None,36.0
1,None,None,106512,[],CHEMBL661128,Inhibitory concentration against cyclin-depend...,B,None,None,BAO_0000190,...,Homo sapiens,Cyclin-dependent kinase 2,9606,None,None,IC50,nM,UO_0000065,None,2.0
2,None,None,107704,[],CHEMBL661128,Inhibitory concentration against cyclin-depend...,B,None,None,BAO_0000190,...,Homo sapiens,Cyclin-dependent kinase 2,9606,None,None,IC50,nM,UO_0000065,None,1000.0
3,None,None,107706,[],CHEMBL661128,Inhibitory concentration against cyclin-depend...,B,None,None,BAO_0000190,...,Homo sapiens,Cyclin-dependent kinase 2,9606,None,None,IC50,nM,UO_0000065,None,1000.0
4,None,None,108039,[],CHEMBL661130,Inhibition of Cyclin-dependent kinase 2,B,None,None,BAO_0000190,...,Homo sapiens,Cyclin-dependent kinase 2,9606,None,None,IC50,uM,UO_0000065,None,0.03

In [8]:
df_all_types.shape

(9050, 46)

In [9]:
# saving the dataframe
df_all_types.to_csv("df_all_targets.csv", index=False, header= True)

In [10]:
# selecting the IC50 only
res2=activity.filter(target_chembl_id=selected_target).filter(standard_type="IC50")
df=pd.DataFrame.from_dict(res2)
df.shape

(2952, 46)

In [11]:
# saving
df.to_csv("df_ic50.csv", index=False, header= True)

In [6]:
9050-2952

6098